version = 1

[merge]
delete_branch_on_merge = true
method = "squash"
# Save GitHub Automation time by only syncing the PR against the default branch if it passes QA control.
optimistic_updates = false
# If a PR is ready more quickly, reward this.
prioritize_ready_to_merge = true

[merge.message]
title = "pull_request_title"
body = "pull_request_body"
include_pull_request_url = true

# We do not want to wait for reviews when a PR is out-of-sync with the default branch. We only want to get to review in-sync code.
update.always = true
